name = "MassBalanceReconciler"
uuid = "e92eb999-f9f6-4ca8-aa98-6cf14c1263f5"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]
version = "0.0.1-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimeRecords = "b543fe20-4c68-4b5f-af79-4641a0d39826"

[compat]
Accessors = "0.1.38"
Clapeyron = "0.6.5"
StaticArrays = "1.9.8"
TimeRecords = "1.3.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
